### ISSUE TITLE
Retrofitting to poky monty

### ISSUE THREAD

**Issue by dtoubelis** [siemens/meta-efibootguard#1]
Would it be possible to retrofit this project to poky monty? I can help with testing.

**Comment by jan-kiszka** [comment]
Doable, I'm open to merge related patches. Please follow up with this discussion on the mailing list.

**Comment by dtoubelis** [comment]
What I found so far is that the binaries are building without any issues but there is a problem with wic plugins because of older version of wic in morty. I forked the repo and will give it a try fixing it myself.

**Comment by dtoubelis** [comment]
It is ready. If you create `morty` branch from `master` I will send pull request.

Alternatively, I can post patch in the group.
