### ISSUE TITLE
dev package for tools

### ISSUE THREAD

**Issue by hoinmic** [siemens/meta-efibootguard#10]
Why is there a dev package for tools? Usually there is one dev package only.

https://github.com/siemens/meta-efibootguard/blob/17730b5bdf7467dca33c5e6a941b6206d9e1f661/recipes-bsp/efibootguard/efibootguard_0.10.bb#L42

**Comment by jan-kiszka** [comment]
Do you refer to the split -dev vs. -staticdev?

**Comment by hoinmic** [comment]
I think we should use the default packages (ex  ${PN}-tools-dev  ->  ${PN}-dev ). A proposal can be found here:
https://groups.google.com/g/efibootguard-dev/c/ud13NWrfnrM

**Comment by jan-kiszka** [comment]
Sure, if that triggers the desired / required magic in OE.

**Comment by hoinmic** [comment]
fixed with 471da1f476b48dcf9e02860c7f30a0a883ec5e19
