### ISSUE TITLE
Update license for yocto kirkstone

### ISSUE THREAD

**Issue by petermarko** [siemens/meta-efibootguard#13]
Building against latest poky master (kirkstone) gives following warning:
```
WARNING: efibootguard-0.10-r0 do_package_qa: QA Issue: Recipe LICENSE includes obsolete licenses GPLv2 [obsolete-license]
```

License should be updated (probably to `GPL-2.0-only`).
Issue with that is that it would also mean losing compatibility with older yocto releases which do not have this license available in common-licenses.

**Comment by hoinmic** [comment]
Thanks for the info. Maybe the time has come and I need to create a branch for dunfell (lts -> until Apr. 2024).

**Comment by hoinmic** [comment]
License in https://github.com/siemens/meta-efibootguard/pull/15 updated. 

I added a branch for [dunfell](https://github.com/siemens/meta-efibootguard/tree/dunfell)
