### ISSUE TITLE
Create `dunfell` branch

### ISSUE THREAD

**Issue by dtoubelis** [siemens/meta-efibootguard#9]
Could you please create `dunfell`  branch in the repository? Two reasons:

- `dunfell` is LTS branch of yocto that is actively maintained
- Latset changes to `master` seem incompatible with yocto-dunfell

**Comment by jan-kiszka** [comment]
Are they or are they not? I'm seeing no move to drop related compat declaration. @hoinmic

**Comment by hoinmic** [comment]
The current version of "dunfell" is compatible with this master branch. 
Are you using a current version of "dunfell"? About two months ago the new syntax was backported to dunfell. That means you can use either the new syntax or the old syntax.

https://github.com/OSSystems/meta-browser/issues/543#issuecomment-912605725

**Comment by hoinmic** [comment]
I have prepared a list of compatible yocto versions in a readme patch:
https://groups.google.com/g/efibootguard-dev/c/3BqqtJja_-g

**Comment by dtoubelis** [comment]
Thanks. All good now.
